/**
 * Mock data for the Recruitment module.
 * Realistic Mexican fleet recruitment context.
 */

export interface PipelineStage {
  id: string;
  name: string;
  order: number;
  color: string;
}

export interface RecruitmentSource {
  id: string;
  name: string;
  type: 'paid' | 'organic' | 'referral' | 'offline';
  costPerLead: number;
  isActive: boolean;
}

export interface CandidateDocument {
  id: string;
  tenantId: string;
  candidateId: string;
  type: string;
  fileName: string;
  fileUrl: string;
  status: 'pending' | 'approved' | 'rejected';
  reviewedBy: string | null;
  reviewedAt: Date | null;
  rejectionReason: string | null;
  uploadedAt: Date;
}

export interface Interview {
  id: string;
  tenantId: string;
  candidateId: string;
  scheduledAt: Date;
  interviewType: 'presencial' | 'videollamada' | 'telefonica';
  location: string | null;
  meetingLink: string | null;
  interviewerId: string;
  interviewerName: string;
  status: 'scheduled' | 'completed' | 'cancelled' | 'no_show';
  score: number | null;
  notes: string | null;
  completedAt: Date | null;
}

export interface Candidate {
  id: string;
  tenantId: string;
  firstName: string;
  lastName: string;
  phone: string;
  email: string;
  city: string;
  zone: string;
  hasUberAccount: boolean;
  hasDidiAccount: boolean;
  hasInDriverAccount: boolean;
  uberRating: number | null;
  didiRating: number | null;
  yearsDriving: number;
  hasLicense: boolean;
  licenseType: string | null;
  licenseExpiry: Date | null;
  preferredShift: 'matutino' | 'vespertino' | 'nocturno' | 'mixto';
  weeklyIncomeGoal: number;
  depositCapacity: number;
  sourceId: string;
  referredByDriverId: string | null;
  notes: string | null;
  stageId: string;
  status: 'active' | 'approved' | 'rejected' | 'withdrawn';
  score: number;
  rejectionReason: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export const PIPELINE_STAGES: PipelineStage[] = [
  { id: 'stage-nuevo', name: 'Nuevo', order: 1, color: '#6366F1' },
  { id: 'stage-contactado', name: 'Contactado', order: 2, color: '#F59E0B' },
  { id: 'stage-entrevista', name: 'Entrevista', order: 3, color: '#3B82F6' },
  { id: 'stage-documentos', name: 'Documentos', order: 4, color: '#8B5CF6' },
  { id: 'stage-aprobado', name: 'Aprobado', order: 5, color: '#10B981' },
];

export const RECRUITMENT_SOURCES: RecruitmentSource[] = [
  {
    id: 'src-facebook',
    name: 'Facebook Ads',
    type: 'paid',
    costPerLead: 85.0,
    isActive: true,
  },
  {
    id: 'src-referidos',
    name: 'Referidos',
    type: 'referral',
    costPerLead: 150.0,
    isActive: true,
  },
  {
    id: 'src-whatsapp',
    name: 'WhatsApp',
    type: 'organic',
    costPerLead: 0.0,
    isActive: true,
  },
  {
    id: 'src-volanteo',
    name: 'Volanteo',
    type: 'offline',
    costPerLead: 45.0,
    isActive: true,
  },
];

const TENANT_ID = 'tenant-default';

export const MOCK_CANDIDATES: Candidate[] = [
  // Stage: Nuevo (5 candidates)
  {
    id: 'cand-001',
    tenantId: TENANT_ID,
    firstName: 'Carlos',
    lastName: 'Hernandez Lopez',
    phone: '+5233101234501',
    email: 'carlos.hernandez@gmail.com',
    city: 'Guadalajara',
    zone: 'Zapopan Norte',
    hasUberAccount: true,
    hasDidiAccount: false,
    hasInDriverAccount: false,
    uberRating: 4.85,
    didiRating: null,
    yearsDriving: 3,
    hasLicense: true,
    licenseType: 'B',
    licenseExpiry: new Date('2027-06-15'),
    preferredShift: 'matutino',
    weeklyIncomeGoal: 5000,
    depositCapacity: 3000,
    sourceId: 'src-facebook',
    referredByDriverId: null,
    notes: 'Interesado en turno de lunes a viernes',
    stageId: 'stage-nuevo',
    status: 'active',
    score: 78,
    rejectionReason: null,
    createdAt: new Date('2026-03-20T09:15:00'),
    updatedAt: new Date('2026-03-20T09:15:00'),
  },
  {
    id: 'cand-002',
    tenantId: TENANT_ID,
    firstName: 'Maria',
    lastName: 'Gonzalez Ramirez',
    phone: '+5255101234502',
    email: 'maria.gonzalez@hotmail.com',
    city: 'CDMX',
    zone: 'Coyoacan',
    hasUberAccount: true,
    hasDidiAccount: true,
    hasInDriverAccount: false,
    uberRating: 4.92,
    didiRating: 4.88,
    yearsDriving: 5,
    hasLicense: true,
    licenseType: 'B',
    licenseExpiry: new Date('2028-01-20'),
    preferredShift: 'vespertino',
    weeklyIncomeGoal: 6000,
    depositCapacity: 5000,
    sourceId: 'src-referidos',
    referredByDriverId: 'driver-012',
    notes: 'Referida por conductor activo. Excelente perfil.',
    stageId: 'stage-nuevo',
    status: 'active',
    score: 92,
    rejectionReason: null,
    createdAt: new Date('2026-03-21T11:30:00'),
    updatedAt: new Date('2026-03-21T11:30:00'),
  },
  {
    id: 'cand-003',
    tenantId: TENANT_ID,
    firstName: 'Roberto',
    lastName: 'Martinez Soto',
    phone: '+5281101234503',
    email: 'roberto.mtz@yahoo.com',
    city: 'Monterrey',
    zone: 'San Pedro',
    hasUberAccount: false,
    hasDidiAccount: false,
    hasInDriverAccount: true,
    uberRating: null,
    didiRating: null,
    yearsDriving: 1,
    hasLicense: true,
    licenseType: 'B',
    licenseExpiry: new Date('2026-09-10'),
    preferredShift: 'nocturno',
    weeklyIncomeGoal: 4000,
    depositCapacity: 2000,
    sourceId: 'src-whatsapp',
    referredByDriverId: null,
    notes: 'Solo experiencia en InDriver',
    stageId: 'stage-nuevo',
    status: 'active',
    score: 42,
    rejectionReason: null,
    createdAt: new Date('2026-03-22T08:00:00'),
    updatedAt: new Date('2026-03-22T08:00:00'),
  },
  {
    id: 'cand-004',
    tenantId: TENANT_ID,
    firstName: 'Ana',
    lastName: 'Torres Vega',
    phone: '+5244201234504',
    email: 'ana.torres@gmail.com',
    city: 'Queretaro',
    zone: 'Centro',
    hasUberAccount: true,
    hasDidiAccount: false,
    hasInDriverAccount: false,
    uberRating: 4.70,
    didiRating: null,
    yearsDriving: 2,
    hasLicense: true,
    licenseType: 'B',
    licenseExpiry: new Date('2027-03-01'),
    preferredShift: 'matutino',
    weeklyIncomeGoal: 4500,
    depositCapacity: 3500,
    sourceId: 'src-volanteo',
    referredByDriverId: null,
    notes: null,
    stageId: 'stage-nuevo',
    status: 'active',
    score: 65,
    rejectionReason: null,
    createdAt: new Date('2026-03-23T14:20:00'),
    updatedAt: new Date('2026-03-23T14:20:00'),
  },
  {
    id: 'cand-005',
    tenantId: TENANT_ID,
    firstName: 'Jose Luis',
    lastName: 'Perez Medina',
    phone: '+5233101234505',
    email: 'joseluis.perez@gmail.com',
    city: 'Guadalajara',
    zone: 'Tlaquepaque',
    hasUberAccount: false,
    hasDidiAccount: true,
    hasInDriverAccount: false,
    uberRating: null,
    didiRating: 4.60,
    yearsDriving: 4,
    hasLicense: false,
    licenseType: null,
    licenseExpiry: null,
    preferredShift: 'mixto',
    weeklyIncomeGoal: 5500,
    depositCapacity: 4000,
    sourceId: 'src-facebook',
    referredByDriverId: null,
    notes: 'Licencia vencida, necesita renovar',
    stageId: 'stage-nuevo',
    status: 'active',
    score: 35,
    rejectionReason: null,
    createdAt: new Date('2026-03-23T16:45:00'),
    updatedAt: new Date('2026-03-23T16:45:00'),
  },

  // Stage: Contactado (5 candidates)
  {
    id: 'cand-006',
    tenantId: TENANT_ID,
    firstName: 'Fernando',
    lastName: 'Diaz Castillo',
    phone: '+5255101234506',
    email: 'fernando.diaz@outlook.com',
    city: 'CDMX',
    zone: 'Iztapalapa',
    hasUberAccount: true,
    hasDidiAccount: true,
    hasInDriverAccount: false,
    uberRating: 4.80,
    didiRating: 4.75,
    yearsDriving: 6,
    hasLicense: true,
    licenseType: 'C',
    licenseExpiry: new Date('2028-05-20'),
    preferredShift: 'matutino',
    weeklyIncomeGoal: 7000,
    depositCapacity: 5000,
    sourceId: 'src-referidos',
    referredByDriverId: 'driver-005',
    notes: 'Conductor experimentado, busca mejor ingreso',
    stageId: 'stage-contactado',
    status: 'active',
    score: 88,
    rejectionReason: null,
    createdAt: new Date('2026-03-15T10:00:00'),
    updatedAt: new Date('2026-03-18T14:30:00'),
  },
  {
    id: 'cand-007',
    tenantId: TENANT_ID,
    firstName: 'Gabriela',
    lastName: 'Ruiz Flores',
    phone: '+5281101234507',
    email: 'gaby.ruiz@gmail.com',
    city: 'Monterrey',
    zone: 'Apodaca',
    hasUberAccount: true,
    hasDidiAccount: false,
    hasInDriverAccount: false,
    uberRating: 4.65,
    didiRating: null,
    yearsDriving: 2,
    hasLicense: true,
    licenseType: 'B',
    licenseExpiry: new Date('2027-11-15'),
    preferredShift: 'vespertino',
    weeklyIncomeGoal: 4500,
    depositCapacity: 2500,
    sourceId: 'src-facebook',
    referredByDriverId: null,
    notes: 'Contactada por WhatsApp, agenda para esta semana',
    stageId: 'stage-contactado',
    status: 'active',
    score: 61,
    rejectionReason: null,
    createdAt: new Date('2026-03-16T12:00:00'),
    updatedAt: new Date('2026-03-19T09:00:00'),
  },
  {
    id: 'cand-008',
    tenantId: TENANT_ID,
    firstName: 'Miguel Angel',
    lastName: 'Sanchez Reyes',
    phone: '+5233101234508',
    email: 'miguelangel.sr@gmail.com',
    city: 'Guadalajara',
    zone: 'Tonala',
    hasUberAccount: true,
    hasDidiAccount: true,
    hasInDriverAccount: true,
    uberRating: 4.90,
    didiRating: 4.85,
    yearsDriving: 7,
    hasLicense: true,
    licenseType: 'C',
    licenseExpiry: new Date('2029-02-28'),
    preferredShift: 'matutino',
    weeklyIncomeGoal: 8000,
    depositCapacity: 6000,
    sourceId: 'src-whatsapp',
    referredByDriverId: null,
    notes: 'Perfil premium, experiencia en tres plataformas',
    stageId: 'stage-contactado',
    status: 'active',
    score: 95,
    rejectionReason: null,
    createdAt: new Date('2026-03-14T08:30:00'),
    updatedAt: new Date('2026-03-17T16:00:00'),
  },
  {
    id: 'cand-009',
    tenantId: TENANT_ID,
    firstName: 'Patricia',
    lastName: 'Moreno Luna',
    phone: '+5244201234509',
    email: 'paty.moreno@yahoo.com',
    city: 'Queretaro',
    zone: 'Juriquilla',
    hasUberAccount: false,
    hasDidiAccount: true,
    hasInDriverAccount: false,
    uberRating: null,
    didiRating: 4.50,
    yearsDriving: 1,
    hasLicense: true,
    licenseType: 'B',
    licenseExpiry: new Date('2027-08-01'),
    preferredShift: 'vespertino',
    weeklyIncomeGoal: 3500,
    depositCapacity: 2000,
    sourceId: 'src-volanteo',
    referredByDriverId: null,
    notes: 'Poco experiencia pero muy motivada',
    stageId: 'stage-contactado',
    status: 'active',
    score: 48,
    rejectionReason: null,
    createdAt: new Date('2026-03-17T11:15:00'),
    updatedAt: new Date('2026-03-20T10:00:00'),
  },
  {
    id: 'cand-010',
    tenantId: TENANT_ID,
    firstName: 'Jorge',
    lastName: 'Vargas Gutierrez',
    phone: '+5255101234510',
    email: 'jorge.vargas@gmail.com',
    city: 'CDMX',
    zone: 'Gustavo A. Madero',
    hasUberAccount: true,
    hasDidiAccount: false,
    hasInDriverAccount: false,
    uberRating: 4.55,
    didiRating: null,
    yearsDriving: 3,
    hasLicense: true,
    licenseType: 'B',
    licenseExpiry: new Date('2026-12-20'),
    preferredShift: 'nocturno',
    weeklyIncomeGoal: 5000,
    depositCapacity: 3000,
    sourceId: 'src-facebook',
    referredByDriverId: null,
    notes: null,
    stageId: 'stage-contactado',
    status: 'active',
    score: 58,
    rejectionReason: null,
    createdAt: new Date('2026-03-18T15:30:00'),
    updatedAt: new Date('2026-03-21T11:00:00'),
  },

  // Stage: Entrevista (4 candidates)
  {
    id: 'cand-011',
    tenantId: TENANT_ID,
    firstName: 'Ricardo',
    lastName: 'Aguilar Rojas',
    phone: '+5233101234511',
    email: 'ricardo.aguilar@gmail.com',
    city: 'Guadalajara',
    zone: 'Zapopan Sur',
    hasUberAccount: true,
    hasDidiAccount: true,
    hasInDriverAccount: false,
    uberRating: 4.88,
    didiRating: 4.82,
    yearsDriving: 5,
    hasLicense: true,
    licenseType: 'C',
    licenseExpiry: new Date('2028-07-10'),
    preferredShift: 'matutino',
    weeklyIncomeGoal: 6500,
    depositCapacity: 5000,
    sourceId: 'src-referidos',
    referredByDriverId: 'driver-018',
    notes: 'Entrevista presencial agendada',
    stageId: 'stage-entrevista',
    status: 'active',
    score: 85,
    rejectionReason: null,
    createdAt: new Date('2026-03-10T09:00:00'),
    updatedAt: new Date('2026-03-18T13:00:00'),
  },
  {
    id: 'cand-012',
    tenantId: TENANT_ID,
    firstName: 'Laura',
    lastName: 'Mendoza Cruz',
    phone: '+5281101234512',
    email: 'laura.mendoza@hotmail.com',
    city: 'Monterrey',
    zone: 'Santa Catarina',
    hasUberAccount: true,
    hasDidiAccount: false,
    hasInDriverAccount: false,
    uberRating: 4.78,
    didiRating: null,
    yearsDriving: 4,
    hasLicense: true,
    licenseType: 'B',
    licenseExpiry: new Date('2027-10-30'),
    preferredShift: 'mixto',
    weeklyIncomeGoal: 5500,
    depositCapacity: 4000,
    sourceId: 'src-facebook',
    referredByDriverId: null,
    notes: 'Videollamada completada, buen perfil',
    stageId: 'stage-entrevista',
    status: 'active',
    score: 74,
    rejectionReason: null,
    createdAt: new Date('2026-03-08T14:00:00'),
    updatedAt: new Date('2026-03-16T10:30:00'),
  },
  {
    id: 'cand-013',
    tenantId: TENANT_ID,
    firstName: 'Eduardo',
    lastName: 'Rios Navarro',
    phone: '+5255101234513',
    email: 'eduardo.rios@gmail.com',
    city: 'CDMX',
    zone: 'Tlalpan',
    hasUberAccount: true,
    hasDidiAccount: true,
    hasInDriverAccount: true,
    uberRating: 4.95,
    didiRating: 4.91,
    yearsDriving: 8,
    hasLicense: true,
    licenseType: 'C',
    licenseExpiry: new Date('2029-04-15'),
    preferredShift: 'matutino',
    weeklyIncomeGoal: 9000,
    depositCapacity: 7000,
    sourceId: 'src-referidos',
    referredByDriverId: 'driver-003',
    notes: 'Perfil excepcional. Entrevista telefonica completada con exito.',
    stageId: 'stage-entrevista',
    status: 'active',
    score: 95,
    rejectionReason: null,
    createdAt: new Date('2026-03-05T10:00:00'),
    updatedAt: new Date('2026-03-14T15:00:00'),
  },
  {
    id: 'cand-014',
    tenantId: TENANT_ID,
    firstName: 'Veronica',
    lastName: 'Castro Ibarra',
    phone: '+5244201234514',
    email: 'vero.castro@gmail.com',
    city: 'Queretaro',
    zone: 'El Marques',
    hasUberAccount: false,
    hasDidiAccount: true,
    hasInDriverAccount: false,
    uberRating: null,
    didiRating: 4.68,
    yearsDriving: 2,
    hasLicense: true,
    licenseType: 'B',
    licenseExpiry: new Date('2027-05-20'),
    preferredShift: 'vespertino',
    weeklyIncomeGoal: 4000,
    depositCapacity: 2500,
    sourceId: 'src-whatsapp',
    referredByDriverId: null,
    notes: 'Entrevista pendiente, confirmar horario',
    stageId: 'stage-entrevista',
    status: 'active',
    score: 55,
    rejectionReason: null,
    createdAt: new Date('2026-03-12T16:00:00'),
    updatedAt: new Date('2026-03-19T11:30:00'),
  },

  // Stage: Documentos (3 candidates)
  {
    id: 'cand-015',
    tenantId: TENANT_ID,
    firstName: 'Alejandro',
    lastName: 'Dominguez Pena',
    phone: '+5233101234515',
    email: 'alex.dominguez@gmail.com',
    city: 'Guadalajara',
    zone: 'Centro',
    hasUberAccount: true,
    hasDidiAccount: true,
    hasInDriverAccount: false,
    uberRating: 4.87,
    didiRating: 4.80,
    yearsDriving: 6,
    hasLicense: true,
    licenseType: 'C',
    licenseExpiry: new Date('2028-09-01'),
    preferredShift: 'matutino',
    weeklyIncomeGoal: 7000,
    depositCapacity: 5500,
    sourceId: 'src-referidos',
    referredByDriverId: 'driver-021',
    notes: 'Documentos en revision, falta comprobante de domicilio',
    stageId: 'stage-documentos',
    status: 'active',
    score: 82,
    rejectionReason: null,
    createdAt: new Date('2026-03-01T09:00:00'),
    updatedAt: new Date('2026-03-15T14:00:00'),
  },
  {
    id: 'cand-016',
    tenantId: TENANT_ID,
    firstName: 'Diana',
    lastName: 'Salazar Ortiz',
    phone: '+5255101234516',
    email: 'diana.salazar@gmail.com',
    city: 'CDMX',
    zone: 'Benito Juarez',
    hasUberAccount: true,
    hasDidiAccount: false,
    hasInDriverAccount: false,
    uberRating: 4.91,
    didiRating: null,
    yearsDriving: 4,
    hasLicense: true,
    licenseType: 'B',
    licenseExpiry: new Date('2028-03-15'),
    preferredShift: 'vespertino',
    weeklyIncomeGoal: 5500,
    depositCapacity: 4000,
    sourceId: 'src-facebook',
    referredByDriverId: null,
    notes: 'Todos los documentos completos, en revision final',
    stageId: 'stage-documentos',
    status: 'active',
    score: 79,
    rejectionReason: null,
    createdAt: new Date('2026-02-25T11:00:00'),
    updatedAt: new Date('2026-03-12T16:30:00'),
  },
  {
    id: 'cand-017',
    tenantId: TENANT_ID,
    firstName: 'Oscar',
    lastName: 'Jimenez Barrera',
    phone: '+5281101234517',
    email: 'oscar.jimenez@outlook.com',
    city: 'Monterrey',
    zone: 'Guadalupe',
    hasUberAccount: true,
    hasDidiAccount: true,
    hasInDriverAccount: true,
    uberRating: 4.93,
    didiRating: 4.89,
    yearsDriving: 9,
    hasLicense: true,
    licenseType: 'C',
    licenseExpiry: new Date('2029-06-30'),
    preferredShift: 'matutino',
    weeklyIncomeGoal: 8500,
    depositCapacity: 6000,
    sourceId: 'src-whatsapp',
    referredByDriverId: null,
    notes: 'INE y licencia aprobadas, falta antecedentes penales',
    stageId: 'stage-documentos',
    status: 'active',
    score: 91,
    rejectionReason: null,
    createdAt: new Date('2026-02-20T08:30:00'),
    updatedAt: new Date('2026-03-10T11:00:00'),
  },

  // Stage: Aprobado (3 candidates)
  {
    id: 'cand-018',
    tenantId: TENANT_ID,
    firstName: 'Sergio',
    lastName: 'Nunez Delgado',
    phone: '+5233101234518',
    email: 'sergio.nunez@gmail.com',
    city: 'Guadalajara',
    zone: 'Zapopan Centro',
    hasUberAccount: true,
    hasDidiAccount: true,
    hasInDriverAccount: false,
    uberRating: 4.89,
    didiRating: 4.84,
    yearsDriving: 5,
    hasLicense: true,
    licenseType: 'C',
    licenseExpiry: new Date('2028-11-20'),
    preferredShift: 'matutino',
    weeklyIncomeGoal: 7000,
    depositCapacity: 5000,
    sourceId: 'src-referidos',
    referredByDriverId: 'driver-007',
    notes: 'Aprobado. Pendiente asignacion de vehiculo.',
    stageId: 'stage-aprobado',
    status: 'approved',
    score: 87,
    rejectionReason: null,
    createdAt: new Date('2026-02-10T09:00:00'),
    updatedAt: new Date('2026-03-05T15:00:00'),
  },
  {
    id: 'cand-019',
    tenantId: TENANT_ID,
    firstName: 'Claudia',
    lastName: 'Rivera Espinosa',
    phone: '+5255101234519',
    email: 'claudia.rivera@gmail.com',
    city: 'CDMX',
    zone: 'Miguel Hidalgo',
    hasUberAccount: true,
    hasDidiAccount: true,
    hasInDriverAccount: false,
    uberRating: 4.96,
    didiRating: 4.93,
    yearsDriving: 7,
    hasLicense: true,
    licenseType: 'C',
    licenseExpiry: new Date('2029-01-10'),
    preferredShift: 'matutino',
    weeklyIncomeGoal: 8000,
    depositCapacity: 6000,
    sourceId: 'src-facebook',
    referredByDriverId: null,
    notes: 'Aprobada. Registro de conductora creado.',
    stageId: 'stage-aprobado',
    status: 'approved',
    score: 94,
    rejectionReason: null,
    createdAt: new Date('2026-02-05T12:00:00'),
    updatedAt: new Date('2026-03-01T10:00:00'),
  },
  {
    id: 'cand-020',
    tenantId: TENANT_ID,
    firstName: 'Arturo',
    lastName: 'Mejia Cordero',
    phone: '+5244201234520',
    email: 'arturo.mejia@hotmail.com',
    city: 'Queretaro',
    zone: 'Corregidora',
    hasUberAccount: true,
    hasDidiAccount: false,
    hasInDriverAccount: false,
    uberRating: 4.82,
    didiRating: null,
    yearsDriving: 3,
    hasLicense: true,
    licenseType: 'B',
    licenseExpiry: new Date('2027-12-05'),
    preferredShift: 'vespertino',
    weeklyIncomeGoal: 5000,
    depositCapacity: 3500,
    sourceId: 'src-volanteo',
    referredByDriverId: null,
    notes: 'Aprobado. Capacitacion programada.',
    stageId: 'stage-aprobado',
    status: 'approved',
    score: 72,
    rejectionReason: null,
    createdAt: new Date('2026-02-15T14:00:00'),
    updatedAt: new Date('2026-03-08T09:30:00'),
  },
];

export const MOCK_INTERVIEWS: Interview[] = [
  {
    id: 'int-001',
    tenantId: TENANT_ID,
    candidateId: 'cand-011',
    scheduledAt: new Date('2026-03-25T10:00:00'),
    interviewType: 'presencial',
    location: 'Oficina Guadalajara - Av. Americas 1254, Col. Country Club',
    meetingLink: null,
    interviewerId: 'user-recruiter-01',
    interviewerName: 'Ana Lucia Vargas',
    status: 'scheduled',
    score: null,
    notes: null,
    completedAt: null,
  },
  {
    id: 'int-002',
    tenantId: TENANT_ID,
    candidateId: 'cand-012',
    scheduledAt: new Date('2026-03-19T15:00:00'),
    interviewType: 'videollamada',
    location: null,
    meetingLink: 'https://meet.google.com/abc-defg-hij',
    interviewerId: 'user-recruiter-02',
    interviewerName: 'Pedro Rios Campos',
    status: 'completed',
    score: 82,
    notes: 'Buena comunicacion, experiencia verificada. Recomendada para siguiente etapa.',
    completedAt: new Date('2026-03-19T15:45:00'),
  },
  {
    id: 'int-003',
    tenantId: TENANT_ID,
    candidateId: 'cand-014',
    scheduledAt: new Date('2026-03-26T11:30:00'),
    interviewType: 'telefonica',
    location: null,
    meetingLink: null,
    interviewerId: 'user-recruiter-01',
    interviewerName: 'Ana Lucia Vargas',
    status: 'scheduled',
    score: null,
    notes: null,
    completedAt: null,
  },
];

export const MOCK_DOCUMENTS: CandidateDocument[] = [
  {
    id: 'doc-001',
    tenantId: TENANT_ID,
    candidateId: 'cand-015',
    type: 'INE',
    fileName: 'ine_alejandro_dominguez.pdf',
    fileUrl: '/uploads/recruitment/cand-015/ine_alejandro_dominguez.pdf',
    status: 'approved',
    reviewedBy: 'user-recruiter-01',
    reviewedAt: new Date('2026-03-12T10:00:00'),
    rejectionReason: null,
    uploadedAt: new Date('2026-03-10T09:00:00'),
  },
  {
    id: 'doc-002',
    tenantId: TENANT_ID,
    candidateId: 'cand-015',
    type: 'Licencia de Conducir',
    fileName: 'licencia_alejandro_dominguez.pdf',
    fileUrl: '/uploads/recruitment/cand-015/licencia_alejandro_dominguez.pdf',
    status: 'approved',
    reviewedBy: 'user-recruiter-01',
    reviewedAt: new Date('2026-03-12T10:05:00'),
    rejectionReason: null,
    uploadedAt: new Date('2026-03-10T09:05:00'),
  },
  {
    id: 'doc-003',
    tenantId: TENANT_ID,
    candidateId: 'cand-015',
    type: 'Comprobante de Domicilio',
    fileName: 'comprobante_domicilio_alex.pdf',
    fileUrl: '/uploads/recruitment/cand-015/comprobante_domicilio_alex.pdf',
    status: 'pending',
    reviewedBy: null,
    reviewedAt: null,
    rejectionReason: null,
    uploadedAt: new Date('2026-03-14T16:00:00'),
  },
  {
    id: 'doc-004',
    tenantId: TENANT_ID,
    candidateId: 'cand-016',
    type: 'INE',
    fileName: 'ine_diana_salazar.pdf',
    fileUrl: '/uploads/recruitment/cand-016/ine_diana_salazar.pdf',
    status: 'approved',
    reviewedBy: 'user-recruiter-02',
    reviewedAt: new Date('2026-03-08T14:00:00'),
    rejectionReason: null,
    uploadedAt: new Date('2026-03-07T11:30:00'),
  },
  {
    id: 'doc-005',
    tenantId: TENANT_ID,
    candidateId: 'cand-016',
    type: 'Licencia de Conducir',
    fileName: 'licencia_diana_salazar.pdf',
    fileUrl: '/uploads/recruitment/cand-016/licencia_diana_salazar.pdf',
    status: 'approved',
    reviewedBy: 'user-recruiter-02',
    reviewedAt: new Date('2026-03-08T14:05:00'),
    rejectionReason: null,
    uploadedAt: new Date('2026-03-07T11:35:00'),
  },
  {
    id: 'doc-006',
    tenantId: TENANT_ID,
    candidateId: 'cand-016',
    type: 'Carta de Antecedentes No Penales',
    fileName: 'antecedentes_diana_salazar.pdf',
    fileUrl: '/uploads/recruitment/cand-016/antecedentes_diana_salazar.pdf',
    status: 'approved',
    reviewedBy: 'user-recruiter-02',
    reviewedAt: new Date('2026-03-10T09:00:00'),
    rejectionReason: null,
    uploadedAt: new Date('2026-03-09T08:00:00'),
  },
  {
    id: 'doc-007',
    tenantId: TENANT_ID,
    candidateId: 'cand-017',
    type: 'INE',
    fileName: 'ine_oscar_jimenez.pdf',
    fileUrl: '/uploads/recruitment/cand-017/ine_oscar_jimenez.pdf',
    status: 'approved',
    reviewedBy: 'user-recruiter-01',
    reviewedAt: new Date('2026-03-06T11:00:00'),
    rejectionReason: null,
    uploadedAt: new Date('2026-03-05T10:00:00'),
  },
  {
    id: 'doc-008',
    tenantId: TENANT_ID,
    candidateId: 'cand-017',
    type: 'Licencia de Conducir',
    fileName: 'licencia_oscar_jimenez.pdf',
    fileUrl: '/uploads/recruitment/cand-017/licencia_oscar_jimenez.pdf',
    status: 'approved',
    reviewedBy: 'user-recruiter-01',
    reviewedAt: new Date('2026-03-06T11:05:00'),
    rejectionReason: null,
    uploadedAt: new Date('2026-03-05T10:05:00'),
  },
  {
    id: 'doc-009',
    tenantId: TENANT_ID,
    candidateId: 'cand-017',
    type: 'Carta de Antecedentes No Penales',
    fileName: 'antecedentes_oscar_jimenez.pdf',
    fileUrl: '/uploads/recruitment/cand-017/antecedentes_oscar_jimenez.pdf',
    status: 'pending',
    reviewedBy: null,
    reviewedAt: null,
    rejectionReason: null,
    uploadedAt: new Date('2026-03-09T15:00:00'),
  },
];

export const MOCK_METRICS = {
  funnel: {
    totalLeads: 156,
    contacted: 98,
    interviewed: 67,
    documentsSubmitted: 42,
    approved: 31,
    conversionRate: 19.87,
  },
  byPeriod: {
    thisWeek: { newLeads: 12, approved: 3, rejected: 2 },
    thisMonth: { newLeads: 48, approved: 11, rejected: 7 },
    lastMonth: { newLeads: 52, approved: 13, rejected: 9 },
  },
  averages: {
    timeToContact: 1.2, // days
    timeToInterview: 4.5, // days
    timeToApproval: 12.3, // days
    scoreAverage: 68.5,
    interviewPassRate: 72.4,
    documentApprovalRate: 88.6,
  },
  bySource: [
    { sourceId: 'src-facebook', sourceName: 'Facebook Ads', leads: 65, approved: 12, cost: 5525.0, costPerHire: 460.42, conversionRate: 18.46 },
    { sourceId: 'src-referidos', sourceName: 'Referidos', leads: 38, approved: 11, cost: 5700.0, costPerHire: 518.18, conversionRate: 28.95 },
    { sourceId: 'src-whatsapp', sourceName: 'WhatsApp', leads: 31, approved: 5, cost: 0.0, costPerHire: 0.0, conversionRate: 16.13 },
    { sourceId: 'src-volanteo', sourceName: 'Volanteo', leads: 22, approved: 3, cost: 990.0, costPerHire: 330.0, conversionRate: 13.64 },
  ],
  byCity: [
    { city: 'Guadalajara', leads: 52, approved: 12, avgScore: 72.3 },
    { city: 'CDMX', leads: 48, approved: 10, avgScore: 69.8 },
    { city: 'Monterrey', leads: 33, approved: 6, avgScore: 65.2 },
    { city: 'Queretaro', leads: 23, approved: 3, avgScore: 61.5 },
  ],
};

export const MOCK_REFERRAL_STATS = {
  totalReferrals: 38,
  activeReferrers: 15,
  conversionRate: 28.95,
  avgBonusPaid: 500.0,
  totalBonusesPaid: 5500.0,
  topReferrers: [
    { driverId: 'driver-003', driverName: 'Eduardo Campos', referrals: 6, hired: 3, bonusEarned: 1500.0 },
    { driverId: 'driver-007', driverName: 'Lucia Fernandez', referrals: 5, hired: 2, bonusEarned: 1000.0 },
    { driverId: 'driver-012', driverName: 'Marco Antonio Silva', referrals: 4, hired: 2, bonusEarned: 1000.0 },
    { driverId: 'driver-018', driverName: 'Isabel Contreras', referrals: 3, hired: 1, bonusEarned: 500.0 },
    { driverId: 'driver-021', driverName: 'Raul Espinoza', referrals: 3, hired: 1, bonusEarned: 500.0 },
  ],
  monthlyTrend: [
    { month: '2026-01', referrals: 10, hired: 3 },
    { month: '2026-02', referrals: 14, hired: 4 },
    { month: '2026-03', referrals: 14, hired: 4 },
  ],
};
